// GitHub/GitLab webhook receiver — near-real-time sync for issue state
// changes made directly on the tracker (someone comments/closes/reopens/
// relabels outside CodeAxis), instead of waiting for periodicTrackingLoop's
// 10-minute cycle (engine/src/issue-tracker.ts). That periodic loop is NOT
// removed — it's the backstop for a missed/failed webhook delivery, which
// GitHub/GitLab explicitly don't guarantee.
//
// Deliberately does NOT re-derive tracker state from the webhook payload
// itself: it only figures out WHICH local issue_submissions row (if any)
// the event is about, then calls pollSubmissionById (issue-tracker.ts) —
// the exact same function issue-routes.ts's own post-action recheck uses.
// One state-computation path, not two that could quietly drift apart.
//
// One shared secret per provider (APP_GITHUB_WEBHOOK_SECRET/
// APP_GITLAB_WEBHOOK_SECRET, auto-generated by loadOrCreate*WebhookSecret
// in config.ts if unset), not a distinct secret per repo — every repo's
// webhook config on that provider uses the same value. A compromised
// secret would let someone trigger recheck-only side effects (a superfluous
// tracker API call), not forge state — the actual state always comes from
// re-fetching the tracker directly, never trusted from the payload.
import type { Hono, Context } from "hono";
import * as crypto from "node:crypto";
import type { DbClient } from "../db/client.js";
import type { Settings } from "../config.js";
import type { Env } from "./app.js";
import { normalizeRepoUrl } from "./admin-routes.js";
import { pollSubmissionById } from "../issue-tracker.js";

export type WebhookRoutesDeps = { db: DbClient; settings: Settings };

async function parseJson(rawBody: string): Promise<Record<string, unknown> | null> {
  try {
    return JSON.parse(rawBody) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function isPlainObject(val: unknown): val is Record<string, unknown> {
  return val !== null && typeof val === "object" && !Array.isArray(val);
}

// Equal-length secrets (both crypto.randomBytes(32).toString("hex"), or a
// GitHub sha256=<64-hex> signature) — the length pre-check below doesn't
// leak anything an attacker could act on, and avoids crypto.timingSafeEqual
// throwing on a length mismatch (it requires equal-length buffers).
function timingSafeEqualStrings(a: string, b: string): boolean {
  const bufA = Buffer.from(a);
  const bufB = Buffer.from(b);
  if (bufA.length !== bufB.length) return false;
  return crypto.timingSafeEqual(bufA, bufB);
}

function verifyGithubSignature(rawBody: string, signatureHeader: string | undefined, secret: string): boolean {
  if (!signatureHeader || !signatureHeader.startsWith("sha256=")) return false;
  const expected = "sha256=" + crypto.createHmac("sha256", secret).update(rawBody).digest("hex");
  return timingSafeEqualStrings(signatureHeader, expected);
}

// Scans every repo this instance tracks for one whose (normalized) url
// matches — small enough list that a full scan is fine (matches
// admin-routes.ts's own duplicate-url check, same normalizeRepoUrl reuse).
async function findRepoIdByUrl(db: DbClient, candidateUrl: string): Promise<number | null> {
  const repos = await db.listReposFull();
  const normalized = normalizeRepoUrl(candidateUrl);
  const match = repos.find((r) => normalizeRepoUrl(r.url) === normalized);
  return match ? match.id : null;
}

// If this repo+issue_number has a tracked submission, recheck it now
// instead of waiting for the next periodic poll. Silently no-ops when
// there's no matching row (an issue CodeAxis was never told about) or no
// matching repo (a webhook for a repo this instance doesn't track) —
// neither is an error.
async function recheckIfTracked(db: DbClient, repoId: number, issueNumber: number): Promise<void> {
  const submission = await db.getSubmissionByIssue(repoId, issueNumber);
  if (submission) await pollSubmissionById(db, submission.id);
}

export function mountWebhookRoutes(app: Hono<Env>, deps: WebhookRoutesDeps): void {
  app.post("/api/webhooks/github", async (c: Context<Env>) => {
    const rawBody = await c.req.text();
    const signature = c.req.header("x-hub-signature-256");
    if (!deps.settings.githubWebhookSecret || !verifyGithubSignature(rawBody, signature, deps.settings.githubWebhookSecret)) {
      return c.json({ detail: "invalid signature" }, 401);
    }

    const payload = await parseJson(rawBody);
    const eventType = c.req.header("x-github-event");
    // Always 200 once signature-verified: GitHub retries/flags failures on
    // non-2xx, and an event we don't recognize or can't parse isn't this
    // endpoint's failure to report.
    if (!payload) return c.json({ ok: true });

    try {
      const isIssueEvent = eventType === "issues";
      const isIssueComment = eventType === "issue_comment" && payload.action === "created";
      if (isIssueEvent || isIssueComment) {
        const repository = payload.repository;
        const issue = payload.issue;
        if (isPlainObject(repository) && isPlainObject(issue) && typeof repository.full_name === "string" && typeof issue.number === "number") {
          const repoId = await findRepoIdByUrl(deps.db, `https://github.com/${repository.full_name}`);
          if (repoId !== null) await recheckIfTracked(deps.db, repoId, issue.number);
        }
      }
    } catch {
      // Best-effort — an internal error here must never surface to GitHub
      // as a failure (that just triggers pointless retries).
    }
    return c.json({ ok: true });
  });

  app.post("/api/webhooks/gitlab", async (c: Context<Env>) => {
    const rawBody = await c.req.text();
    const token = c.req.header("x-gitlab-token");
    if (!deps.settings.gitlabWebhookSecret || !token || !timingSafeEqualStrings(token, deps.settings.gitlabWebhookSecret)) {
      return c.json({ detail: "invalid token" }, 401);
    }

    const payload = await parseJson(rawBody);
    if (!payload) return c.json({ ok: true });

    try {
      const project = payload.project;
      const isIssueEvent = payload.object_kind === "issue" && isPlainObject(payload.object_attributes);
      const isNoteOnIssue =
        payload.object_kind === "note" &&
        isPlainObject(payload.object_attributes) &&
        payload.object_attributes.noteable_type === "Issue";

      if (isPlainObject(project) && typeof project.web_url === "string") {
        let issueIid: number | null = null;
        if (isIssueEvent) {
          const attrs = payload.object_attributes as Record<string, unknown>;
          if (typeof attrs.iid === "number") issueIid = attrs.iid;
        } else if (isNoteOnIssue && isPlainObject(payload.issue) && typeof payload.issue.iid === "number") {
          issueIid = payload.issue.iid;
        }
        if (issueIid !== null) {
          const repoId = await findRepoIdByUrl(deps.db, project.web_url);
          if (repoId !== null) await recheckIfTracked(deps.db, repoId, issueIid);
        }
      }
    } catch {
      // Best-effort, same rationale as the GitHub handler above.
    }
    return c.json({ ok: true });
  });
}
